exclude: '^$'
fail_fast: false
repos:
-   repo: https://github.com/python/black
    rev: '19.3b0'
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.701'
    hooks:
    -   id: mypy
        stages: [manual]
    # TODO --disallow-incomplete-defs
        args: [--ignore-missing-imports]