repos:
-   repo: https://github.com/python/black
    rev: '19.3b0'
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.701'
    hooks:
    -   id: mypy
        name: mypy-ml-agents
        files: "ml-agents/.*"
        # TODO --disallow-incomplete-defs
        args: [--ignore-missing-imports]
    -   id: mypy
        name: mypy-ml-agents-envs
        files: "ml-agents-envs/.*"
        args: [--ignore-missing-imports]
    -   id: mypy
        name: mypy-gym-unity
        files: "gym-unity/.*"
        args: [--ignore-missing-imports]