version: 2.1
executors:
  python361:
    docker:
      - image: circleci/python:3.6.1
  python373:
    docker:
      - image: circleci/python:3.7.3

jobs:
  build_python:
    parameters:
      e:
        type: executor
      pyversion:
        type: string
    executor: << parameters.e >>
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-py<< parameters.pyversion >>-{{ checksum "ml-agents/setup.py" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-py<< parameters.pyversion >>-

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade setuptools
            pushd ml-agents-envs && pip install -e . && popd
            pushd ml-agents && pip install -e . && popd
            pip install -r test_requirements.txt
            pushd gym-unity && pip install -e . && popd

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-py<< parameters.pyversion >>-{{ checksum "ml-agents/setup.py" }}

      - run:
          name: Run Tests for ml-agents and gym_unity
          command: |
            . venv/bin/activate
            mkdir test-reports
            pip freeze > test-reports/pip_versions.txt
            pytest --cov=ml-agents --cov=ml-agents-envs --cov=gym-unity --cov-report html --junitxml=test-reports/junit.xml -p no:warnings

      - run:
          name: Check Code Style using pre-commit
          command: |
            . venv/bin/activate
            pre-commit run --show-diff-on-failure --all-files

      - run:
          name: Verify there are no hidden/missing metafiles.
          # Renaming files or deleting files can leave metafiles behind that makes Unity very unhappy.
          command: |
            . venv/bin/activate
            python utils/validate_meta_files.py

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_artifacts:
          path: htmlcov
          destination: htmlcov

workflows:
  workflow:
    jobs:
      - build_python:
          name: python3.6.1
          e: python361
          pyversion: 3.6.1
      - build_python:
          name: python3.7.3
          e: python373
          pyversion: 3.7.3
