{% metadata_file .yamato/test_versions.metafile %}
---
{% for editor in test_editors %}
test_linux_training_int_{{ editor.version }}:
  name: Test Linux Fast Training {{ editor.version }}
  agent:
    type: Unity::VM
    image: package-ci/ubuntu:stable
    flavor: b1.medium
  variables:
    UNITY_VERSION: {{ editor.version }}
  commands:
    - |
      sudo apt-get update && sudo apt-get install -y python3-venv
      python3 -m venv venv && source venv/bin/activate
      python -m pip install pyyaml --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple
      python -m pip install unity-downloader-cli --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple --upgrade
      unity-downloader-cli -u {{ editor.version }} -c editor --wait --fast
      python -u -m ml-agents.tests.yamato.training_int_tests
  dependencies:
    - .yamato/standalone-build-test.yml#test_linux_standalone_{{ editor.version }}
  triggers:
    cancel_old_ci: true
    expression: |
      (pull_request.target eq "master" OR
      pull_request.target match "release.+") AND
      NOT pull_request.draft AND
      (pull_request.changes.any match "com.unity.ml-agents/**" OR
      pull_request.changes.any match "com.unity.ml-agents.extensions/**" OR
      pull_request.changes.any match "Project/**" OR
      pull_request.changes.any match "ml-agents/**" OR
      pull_request.changes.any match "ml-agents-envs/**" OR
      pull_request.changes.any match ".yamato/training-int-tests.yml") AND
      NOT pull_request.changes.all match "**/*.md"
  artifacts:
    logs:
      paths:
        - "artifacts/standalone_build.txt"
        - "artifacts/inference.nn.txt"
        - "artifacts/inference.onnx.txt"
    standalonebuild:
      paths:
        - "artifacts/testPlayer*/**"
        - "artifacts/models/**"
{% endfor %}


test_mac_backcompat_2020.1:
  {% capture editor_version %} 2020.1 {% endcapture %}
  {% capture csharp_backcompat_version %} 1.0.0 {% endcapture %}
  # This test has to run on mac because it requires the custom build of tensorflow without AVX
  # Test against 2020.1 because 2020.2 has to run against package version 1.2.0
  name: Test Mac Backcompat Training {{ editor_version }}
  agent:
    type: Unity::VM::osx
    image: ml-agents/ml-agents-bokken-mac:0.1.4-492264
    flavor: b1.small
  variables:
    UNITY_VERSION: {{ editor_version }}
  commands:
    - |
      python3 -m venv venv && source venv/bin/activate
      python -m pip install pyyaml --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple
      python -m pip install unity-downloader-cli --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple --upgrade
      unity-downloader-cli -u {{ editor_version }} -c editor --wait --fast
      # Backwards-compatibility tests.
      # If we make a breaking change to the communication protocol, these will need
      # to be disabled until the next release.
      python -u -m ml-agents.tests.yamato.standalone_build_tests --build-target=mac
      python -u -m ml-agents.tests.yamato.training_int_tests --csharp={{ csharp_backcompat_version }}
      deactivate
      python3 -m venv venv_old && source venv_old/bin/activate
      python -u -m ml-agents.tests.yamato.training_int_tests --python==0.16.0
  triggers:
    cancel_old_ci: true
    expression: |
      (pull_request.target eq "master" OR
      pull_request.target match "release.+") AND
      NOT pull_request.draft AND
      (pull_request.changes.any match "com.unity.ml-agents/**" OR
      pull_request.changes.any match "com.unity.ml-agents.extensions/**" OR
      pull_request.changes.any match "Project/**" OR
      pull_request.changes.any match "ml-agents/**" OR
      pull_request.changes.any match "ml-agents-envs/**" OR
      pull_request.changes.any match ".yamato/training-int-tests.yml") AND
      NOT pull_request.changes.all match "**/*.md"
  artifacts:
    logs:
      paths:
        - "artifacts/standalone_build.txt"
        - "artifacts/inference.nn.txt"
        - "artifacts/inference.onnx.txt"
    standalonebuild:
      paths:
        - "artifacts/testPlayer*/**"
        - "artifacts/models/**"
